### ISSUE TITLE
Error running 03a_path_propagation_basic

### ISSUE THREAD

**Issue by pmcculey** [bwinkel/pycraf#36]
I'm sure I'm not seeing something basic......

In cell 186 I get the following error:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-186-16974751284c> in <module>
     29 
     30     tot_loss = pathprof.loss_complete(pprop, G_t, G_r)
---> 31     attens[idx] = apu.Quantity(tot_loss).value

ValueError: setting an array element with a sequence.

**Comment by bwinkel** [comment]
Thank you @pmcculey. I think you took the notebook from an older release, right? I fixed the issue with the JSON error, so you should be able to download the [notebook from master](https://raw.githubusercontent.com/bwinkel/pycraf/master/notebooks/03a_path_propagation_basic.ipynb), which has the above issue corrected (needs a tuple around the rvalue: `attens[idx] = apu.Quantity(tot_loss).value`). Please let us know, if this fixes it.
