### ISSUE TITLE
Matplotlib 3.3.3 -- 03c_attenuation_maps failing

### ISSUE THREAD

**Issue by cbowers1020** [bwinkel/pycraf#37]
When running example notebook 03c_attenuation_maps, the color bar fails to render correctly with the proper tick placement, labels, and number of ticks. This occurs in code cell 8:
`ValueError: The number of FixedLocator locations (5), usually from a call to set_ticks, does not match the number of ticklabels (7).`

I am using Matplotlib 3.3.3 on Ubuntu 18 in python 3.6.9.

**Comment by cbowers1020** [comment]
The notebooks work under matplotlib 3.2.2

**Comment by bwinkel** [comment]
Thanks a lot for the hint. New matplotlib versions keep being maintenance heavy... I'll fix this in the next release.

**Comment by cbowers1020** [comment]
I actually found the fix for this. It was painfully simple. The default vmax for the cim object was 950, but the colorbar was setting ticks up to 1350, so changing those to match (either one) fixed the problem.

That being said, it appears the pathprof wrapper function terrain_cmap_factory only takes an optional vmax argument but no vmin. This now causes a warning from matplotlib (attached). When using the color norm created for the terrain, matplotlib now wants vmin and vmax to be set when creating the norm.
![Screen Shot 2021-07-30 at 1 02 17 PM](https://user-images.githubusercontent.com/29465998/127687407-7523cee1-2b12-4cd3-b206-e9721a67232f.png)

**Comment by bwinkel** [comment]
Good to know. I stumbled upon the first problem myself recently, when I updated matplotlib. I'll take care of it asap.
