### ISSUE TITLE
CPLE_OpenFailedError

### ISSUE THREAD

**Issue by enkere87** [bwinkel/pycraf#42]
I am running into an 'openFailedError' on line 6. Rasterio seems to be expecting a different type of file since it can't open CORINE_GEOTIFF.
Also, I am getting a number of errors from this file, 52 to be exact. I am using Google Colab, and I was not able to incorporate the 'Corine Land Cover' into the file. That would explain some of the errors related to the display of figures, but the number of errors is too high. Could you rerun the file to make sure it is still up to date?(https://colab.research.google.com/drive/18QtSniOV7DIqPdMxQny7RTaR7CPrO58u?usp=sharing)

**Comment by bwinkel** [comment]
Hi @enkere87, thanks a lot for the report. I'll look into both of your issues asap. Had you downloaded the Corine file, before working on the notebook? It's something, that the notebook doesn't do automatically... (Which is why it won't be simple to run on colab, as is.)

**Comment by bwinkel** [comment]
After accessing your notebook on Colab, it is clear that you didn't download the Corine data first. I'm not sure, why all the explanatory text is missing in your version of the Notebook. If you look at the notebook on GH or [nbviewer](https://nbviewer.jupyter.org/github/bwinkel/pycraf/blob/master/notebooks/03f_working_with_clutter.ipynb), it tells you right at the top, that you first need to download the data file. This [blog post](https://towardsdatascience.com/google-colab-import-and-export-datasets-eccf801e2971) could help you to find out, how to upload the Corine data to colab. (I'm not very familiar with this...)

I'm closing this issue, as it is not really related with the pycraf package itself.
