### ISSUE TITLE
03e_parameter_dependence

### ISSUE THREAD

**Issue by enkere87** [bwinkel/pycraf#43]
I am running the file and I am getting a NameError message on lines 7 and 9. they both involve the seventh input of the line.
(https://colab.research.google.com/drive/1mSD-7jcxGm80ZlLyOJuh7sP3jj4r7WM7?usp=sharing)

**Comment by bwinkel** [comment]
I'm not sure why, but in your colab version of the notebook, Cell 4 is missing, which contains
```python
hprof_data = pathprof.height_path_data_generic(
    distance, hprof_step, lon_t, lat_t,
    )
```
as can be seen [here](https://nbviewer.jupyter.org/github/bwinkel/pycraf/blob/master/notebooks/03e_parameter_dependence.ipynb). Did you delete that by accident? Perhaps, you can double check, that you did not modify something else, which is important.
