### ISSUE TITLE
pycraf doesn't install with conda when python >= 3.8

### ISSUE THREAD

**Issue by gabicca** [bwinkel/pycraf#46]
Here is the output, for python3.9, on MacOS Mojave:

```
$ conda install -c conda-forge pycraf 

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                             

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - pycraf -> python[version='>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']

Your python: python=3.9

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.
```

conda version:
`4.9.2`

**Comment by bwinkel** [comment]
See #45. I'll try to get this to work as soon as possible, but it's hard without access to a Mac... If you want, you could try to install from the sources, see [here](https://bwinkel.github.io/pycraf/latest/install.html).

**Comment by gabicca** [comment]
> See #45. I'll try to get this to work as soon as possible, but it's hard without access to a Mac... If you want, you could try to install from the sources, see [here](https://bwinkel.github.io/pycraf/latest/install.html).

Thanks, I did try installing from source, and that didn't work either, though the error was different. I spent quite a lot of time trying to install pycraf in different ways, with no success. Conda seems to be the most straightforward way of installing pycraf, hence why I hoped that would work...

**Comment by gabicca** [comment]
@bwinkel I could try helping you with the debug if you explain what I should do (what you would do) and what to look out for.

**Comment by bwinkel** [comment]
> 
> 
> @bwinkel I could try helping you with the debug if you explain what I should do (what you would do) and what to look out for.

We could certainly try that, but unfortunately it will have to wait 2-3 weeks, as I'm really busy right now.

Would working with Python 3.7 be an option? (With conda, one can relatively easily make a dedicated environment just for that, if you don't want to mess around with your other software.)

**Comment by gabicca** [comment]
> > @bwinkel I could try helping you with the debug if you explain what I should do (what you would do) and what to look out for.
> 
> We could certainly try that, but unfortunately it will have to wait 2-3 weeks, as I'm really busy right now.
> 
> Would working with Python 3.7 be an option? (With conda, one can relatively easily make a dedicated environment just for that, if you don't want to mess around with your other software.)

Yes, that's what I've reverted to do for the moment. I can't see a problem with that for now, so hopefully it can wait a few weeks. Thanks!

**Comment by gabicca** [comment]
FYI, `pycraf==2.0.1` installs now on MacOS M1, OS12, with python 3.10. So I'll close this issue. I haven't tested with 3.9 though.
